table Medidas
	lineageTag: e47fd973-b05d-4535-9d1e-1ebf83ff8df2

	measure usuario = ```
			
			
			VAR UsuarioCompleto = USERPRINCIPALNAME()
			VAR UsuarioSemDominio = LEFT(UsuarioCompleto, SEARCH("@", UsuarioCompleto, 1) - 1)
			VAR UsuarioComEspacos = SUBSTITUTE(UsuarioSemDominio, ".", " ")
			
			VAR PalavrasSeparadas = SUBSTITUTE(UsuarioComEspacos, " ", "|")
			VAR ListaPalavras = 
			    ADDCOLUMNS(
			        GENERATESERIES(1, PATHLENGTH(PalavrasSeparadas)),
			        "Palavra", PATHITEM(PalavrasSeparadas, [Value])
			    )
			VAR NomeCapitalizado = 
			    CONCATENATEX(
			        ListaPalavras,
			        UPPER(LEFT([Palavra], 1)) & LOWER(MID([Palavra], 2, LEN([Palavra]))),
			        " "
			    )
			RETURN NomeCapitalizado
			```
		lineageTag: 466a4662-7e3d-403d-80f5-4fad6404b902

	column 'Coluna 1'
		dataType: string
		isHidden
		lineageTag: 447e2b4c-d5ef-4d82-ad4f-68851df1f7d2
		summarizeBy: none
		sourceColumn: Coluna 1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

